const SEGMENTS_CONTAINER = {
    "base_14" : [a, b, c, d, e, f, g, h, i, j, k, l, m, n],
    "base_8" : [a, b, c, d, e, f, g, h]
}

const SEGMENTS_NUMBERS = {
    "0" : [a, b, c, d, e, f, k, l],
    "1" : [b, c],
    "2" : [a, b, d, e, g, h],
    "3" : [a, b, c, d, h],
    "4" : [b, c, f, g, h],
    "5" : [a, c, d, f, g, h],
    "6" : [a, c, d, e, f, g, h],
    "7" : [a, b, c],
    "8" : [a, b, c, d, e, f, g, h],
    "9" : [a, b, c, d, f, g, h]
};

const SEGMENTS_LETTERS_UPPER = {
    "A" : [a, b, c, e, f, g, h],
    "B" : [a, b, c, d, h, j, m],
    "C" : [a, d, e, f],
    "D" : [a, b, c, d, j, m],
    "E" : [a, d, e, f, g],
    "F" : [a, e, f, g],
    "G" : [a, c, d, e, f, h],
    "H" : [b, c, e, f, g, h],
    "I" : [a, d, j, m],
    "J" : [b, c, d, e],
    "K" : [c, e, f, g, h, k],
    "L" : [d, e, f],
    "M" : [b, c, e, f, i, k],
    "N" : [b, c, e, f, i, n],
    "O" : [a, b, c, d, e, f],
    "P" : [a, b, e, f, g, h],
    "Q" : [a, b, c, d, e, f, n],
    "R" : [a, b, e, f, g, h, n],
    "S" : [a, c, d, f, g, h],
    "T" : [a, j, m],
    "U" : [b, c, d, e, f],
    "V" : [e, f, k, l],
    "W" : [b, c, e, f, l, n],
    "X" : [i, k, l, n],
    "Y" : [b, c, d, f, g, h],
    "Z" : [a, d, g, h, k, l],
};

const SEGMENTS_LETTERS_LOWER = {
    "a" : [d, e, g, m],
    "b" : [d, e, f, g, n],
    "c" : [d, e, g, h],
    "d" : [b, c, d, h, l],
    "e" : [d, e, g, l],
    "f" : [g, h, k, m],
    "g" : [b, c, d, h, k],
    "h" : [e, f, g, m],
    "i" : [m],
    "j" : [e, j, l],
    "k" : [h, j, m, n],
    "l" : [e, f],
    "m" : [c, e, g, h, m],
    "n" : [e, g, m],
    "o" : [c, d, e, g, h],
    "p" : [a, e, f, g, k],
    "q" : [a, b, c, h, i],
    "r" : [e, g],
    "s" : [d, h, n],
    "t" : [d, e, f, g],
    "u" : [c, d, e],
    "v" : [e, l],
    "w" : [c, d, e, m],
    "x" : [i, k, l, n],
    "y" : [b, c, d, h, j],
    "z" : [d, g, l],
};

const SEGMENTS_SYMBOLS = {
    "hyphen" : [g, h],
    "slash" : [k, l],
    "apostrophe" : [j],
    "single_quote" : [j],
    "double_quote" : [b, j],
    "cipher" : [a, c, d, f, g, h, k, m],
    "e_comercial" : [a, d, e, g, i, j, n],
    "gt" : [k, n],
    "lt" : [i, l],
    "asterisk" : [g, h, i, j, k, l, m, n],
    "plus" : [g, h, j, m],
    "minus" : [g, h],
    "times" : [i, k, l, n],
    "divide" : [g, h, k, l],
    "degree" : [a, b, f, g, h],
    "underscore" : [d],
    "equal" : [d, g, h],
    "question_mark" : [a, b, h, m],
    "at" : [a, b, d, e, f, h, j],
    "parentheses_open" : [a, f, e, d],
    "parentheses_close" : [a, b, c, d],
    "sum" : [a, d, i, l],
    "braces_open" : [a, d, g, i, l],
    "braces_close" : [a, d, h, k, n],
    "percentage" : [c, f, k, l],
    "exclamation_mark" : [j, m],
    "dot" : [dot]
};